import { motion } from "framer-motion";
import { BriefcaseBusiness, MapPin, CalendarDays } from "lucide-react";

const experiences = [
  { company: "PRODEB — Companhia de Processamento de Dados da Bahia", role: "Analista de Sistemas e Desenvolvedor (Consultor IV)", period: "mar/2024 – set/2024", location: "Salvador/BA", description: "Desenvolvimento e manutenção de soluções web para órgãos públicos estaduais, colaborando na evolução de funcionalidades, integrações e processos de modernização em ambiente ágil.", tags: ["Sistemas web", "APIs", "Banco de dados", "Scrum"] },
  { company: "LAMPP IT Solutions", role: "Analista de Sistemas e Desenvolvedor de Software", period: "mar/2022 – mai/2022", location: "Salvador/BA", description: "Atuação na construção de soluções integradas para ambientes de alta responsabilidade, com atenção à segurança, integridade de dados e qualidade das entregas.", tags: ["Integrações", "Segurança", "APIs", "Qualidade"] },
  { company: "EDZA Planejamento Consultoria e Informática LTDA", role: "Analista de Sistemas e Desenvolvedor de Software", period: "nov/2019 – mar/2022", location: "Salvador/BA", description: "Desenvolvimento de sistemas de gestão pública e sustentação de produtos para diferentes municípios, participando da evolução de regras de negócio e operações críticas.", tags: ["Gestão pública", "Regras de negócio", "Dados", "Agile"] },
];

export function ExperienceSection() {
  return <section id="experience" className="py-24 relative border-y border-border overflow-hidden"><div className="absolute inset-0 rails-grid opacity-20 pointer-events-none" /><div className="container mx-auto px-4 relative"><p className="text-xs font-mono text-primary uppercase tracking-[0.24em] mb-3">Trajetória</p><h2 className="text-3xl md:text-4xl font-bold tracking-tighter">Experiência que fortalece cada entrega.</h2><div className="mt-10 max-w-4xl space-y-5">{experiences.map((item, index) => <motion.article key={item.company} initial={{ opacity: 0, x: -20 }} whileInView={{ opacity: 1, x: 0 }} viewport={{ once: true }} transition={{ delay: index * .1 }} className="rails-experience-card rounded-xl p-5 sm:p-6 grid md:grid-cols-[11rem_1fr] gap-5"><div className="font-mono text-xs text-muted-foreground space-y-3"><span className="flex items-center gap-2"><CalendarDays size={14} className="text-primary" />{item.period}</span><span className="flex items-center gap-2"><MapPin size={14} className="text-primary" />{item.location}</span></div><div><div className="flex gap-3"><BriefcaseBusiness className="text-primary shrink-0 mt-1" size={18} /><div><h3 className="font-bold text-lg">{item.role}</h3><p className="text-sm text-primary mt-1">{item.company}</p></div></div><p className="text-sm text-muted-foreground leading-relaxed mt-4">{item.description}</p><div className="flex flex-wrap gap-2 mt-4">{item.tags.map(tag => <span key={tag} className="text-[10px] font-mono px-2 py-1 rounded border border-primary/25 bg-primary/5 text-primary">{tag}</span>)}</div></div></motion.article>)}</div></div></section>;
}
