import { motion } from "framer-motion";
import { Github, ExternalLink, ArrowUpRight } from "lucide-react";
import { SiRuby, SiRubyonrails, SiPostgresql } from "react-icons/si";

const GITHUB = "https://github.com/reinaldobarreto31";
const projects = [
  { title: "Rails Link Shortener", subtitle: "Encurtador de URLs", description: "Aplicacao Ruby on Rails para criar, organizar e redirecionar links curtos. Um projeto enxuto que demonstra modelagem, rotas e o ciclo completo de uma aplicacao Rails.", tech: ["Ruby", "Rails", "PostgreSQL", "MVC"], icon: SiRubyonrails, tone: "tech-rails", github: `${GITHUB}/rails-link-shortener` },
  { title: "Rails Tasks API", subtitle: "API de tarefas", description: "API REST para gestao de tarefas, estruturada com convencoes Rails, endpoints claros e persistencia em banco de dados relacional.", tech: ["Ruby", "Rails API", "PostgreSQL", "REST"], icon: SiRuby, tone: "tech-ruby", github: `${GITHUB}/rails-tasks-api` },
  { title: "Ruby Expense Tracker", subtitle: "Controle financeiro", description: "Projeto em Ruby voltado ao controle de despesas e a logica de negocio, com uma base simples e legivel para evoluir em uma aplicacao Rails completa.", tech: ["Ruby", "Dominio", "CLI", "Testes"], icon: SiPostgresql, tone: "tech-postgres", github: `${GITHUB}/ruby-expense-tracker` },
];

export function ProjectsSection() {
  return <section id="projects" className="py-24 bg-background"><div className="container mx-auto px-4"><div className="flex flex-col md:flex-row md:items-end justify-between gap-5 mb-12"><div><p className="text-xs font-mono text-primary uppercase tracking-[.24em] mb-3">Portfolio Rails</p><h2 className="text-3xl md:text-4xl font-bold tracking-tighter">Projetos selecionados</h2><p className="text-muted-foreground mt-3 max-w-xl">Projetos que evidenciam uma base solida em Ruby e Ruby on Rails.</p></div><a href={GITHUB} target="_blank" rel="noopener noreferrer" className="inline-flex items-center gap-2 self-start md:self-auto border border-border hover:border-primary/50 px-4 py-2 rounded-lg text-sm text-muted-foreground hover:text-primary transition-colors"><Github size={16} /> Ver GitHub</a></div><div className="grid md:grid-cols-3 gap-5">{projects.map((project, index) => { const Icon = project.icon; return <motion.article key={project.title} initial={{ opacity: 0, y: 22 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }} transition={{ delay: index * .1 }} whileHover={{ y: -7 }} onClick={() => window.open(project.github, "_blank", "noopener,noreferrer")} onKeyDown={(event) => { if (event.key === "Enter" || event.key === " ") window.open(project.github, "_blank", "noopener,noreferrer"); }} role="link" tabIndex={0} className={`rails-project-card ${project.tone} rounded-xl overflow-hidden flex flex-col cursor-pointer`}><div className="h-28 relative flex items-center justify-center rails-project-head"><Icon className="tech-icon text-5xl relative z-10" /><div className="absolute inset-0 rails-grid opacity-50" /></div><div className="p-5 flex flex-col flex-1"><p className="tech-label text-xs font-mono">{project.subtitle}</p><h3 className="font-bold text-lg mt-1">{project.title}</h3><p className="text-sm text-muted-foreground leading-relaxed mt-3 flex-1">{project.description}</p><div className="flex flex-wrap gap-1.5 mt-5">{project.tech.map(tech => <span key={tech} className="tech-tag text-[10px] font-mono px-2 py-1 rounded border">{tech}</span>)}</div><a href={project.github} target="_blank" rel="noopener noreferrer" onClick={(event) => event.stopPropagation()} className="mt-5 inline-flex items-center gap-2 text-sm font-medium text-muted-foreground hover:text-foreground transition-colors">Ver repositorio <ArrowUpRight size={15} /></a></div></motion.article>})}</div><div className="mt-10 text-center"><a href={GITHUB} target="_blank" rel="noopener noreferrer" className="rails-button inline-flex items-center gap-2 px-5 py-3 rounded-lg text-sm">Mais projetos no GitHub <ExternalLink size={15} /></a></div></div></section>;
}
