import { useState } from "react";
import { motion } from "framer-motion";
import { SiRuby, SiRubyonrails, SiPostgresql, SiDocker } from "react-icons/si";
import { RotateCcw, ExternalLink } from "lucide-react";

const STACK = [
  { name: "Ruby", tagline: "Linguagem expressiva", icon: SiRuby, tone: "tech-ruby", detail: "Codigo legivel, orientado a objetos e pensado para entregar valor rapidamente.", points: ["Ruby 3.x", "POO", "Rake", "Bundler"] },
  { name: "Ruby on Rails", tagline: "Framework principal", icon: SiRubyonrails, tone: "tech-rails", detail: "Aplicacoes web completas com convencoes solidas, seguranca e manutencao simples.", points: ["Rails 7 / 8", "MVC", "Active Record", "Hotwire"] },
  { name: "PostgreSQL", tagline: "Dados consistentes", icon: SiPostgresql, tone: "tech-postgres", detail: "Modelagem, consultas e migrations para bases de dados prontas para crescer.", points: ["SQL", "Migrations", "Indices", "Backups"] },
  { name: "Entrega", tagline: "Qualidade continua", icon: SiDocker, tone: "tech-docker", detail: "Ambientes reproduziveis e automacao para publicar com previsibilidade.", points: ["Docker", "Git", "CI/CD", "Testes"] },
];

export function StackShowcaseSection() {
  const [activeCard, setActiveCard] = useState<number | null>(null);
  return <section id="stack" className="py-24 relative bg-card/30 overflow-hidden"><div className="absolute inset-0 pointer-events-none rails-grid opacity-30" /><div className="container mx-auto px-4 relative"><div className="max-w-2xl mb-12"><p className="text-xs font-mono text-primary uppercase tracking-[.24em] mb-3">Stack principal</p><h2 className="text-3xl md:text-4xl font-bold tracking-tighter">Ruby on Rails, do dominio ao deploy.</h2><p className="text-muted-foreground mt-3 leading-relaxed">Clique em um card para revelar seus fundamentos. Cada camada tem sua propria identidade visual.</p></div><div className="grid sm:grid-cols-2 lg:grid-cols-4 gap-5">{STACK.map((item, index) => { const Icon = item.icon; const active = activeCard === index; return <motion.button type="button" key={item.name} initial={{ opacity: 0, y: 22 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }} transition={{ delay: index * .08 }} onClick={() => setActiveCard(active ? null : index)} aria-pressed={active} className={`rails-stack-card ${item.tone} ${active ? "is-active" : ""} group rounded-xl p-5 min-h-64 flex flex-col text-left`}><div className="flex items-start justify-between"><div className="rails-icon p-3 rounded-xl"><Icon className="tech-icon text-3xl" /></div><RotateCcw size={15} className={`text-muted-foreground transition-all duration-500 ${active ? "rotate-180 text-foreground" : "group-hover:text-foreground group-hover:rotate-180"}`} /></div><p className="tech-label text-xs font-mono mt-6">{active ? "Fundamentos" : item.tagline}</p><h3 className="text-xl font-bold mt-1">{item.name}</h3>{active ? <div className="flex flex-wrap gap-1.5 mt-4">{item.points.map(point => <span key={point} className="tech-tag text-[10px] font-mono px-2 py-1 rounded border">{point}</span>)}</div> : <><p className="text-sm leading-relaxed text-muted-foreground mt-3">{item.detail}</p><span className="mt-auto pt-5 text-[10px] font-mono text-muted-foreground">clique para explorar +</span></>}</motion.button>})}</div><a href="#projects" className="mt-9 inline-flex items-center gap-2 text-sm text-muted-foreground hover:text-primary transition-colors">Explorar projetos Rails <ExternalLink size={15} /></a></div></section>;
}
