import { motion } from "framer-motion";
import { Mail, Linkedin, Github, MapPin, ArrowUpRight } from "lucide-react";

const links = [
  { label: "E-mail", value: "reinaldobarretosilva@gmail.com", href: "mailto:reinaldobarretosilva@gmail.com", icon: Mail },
  { label: "LinkedIn", value: "linkedin.com/in/reinaldo-barreto-2a4ba2116", href: "https://linkedin.com/in/reinaldo-barreto-2a4ba2116", icon: Linkedin },
  { label: "GitHub", value: "github.com/reinaldobarreto31", href: "https://github.com/reinaldobarreto31", icon: Github },
];

export function ContactSection() {
  return <section id="contact" className="py-24 bg-background"><div className="container mx-auto px-4 max-w-5xl"><div className="neo-panel rounded-2xl p-7 sm:p-10 relative overflow-hidden"><div className="absolute inset-0 neo-grid opacity-30 pointer-events-none" /><div className="relative grid md:grid-cols-[1.1fr_.9fr] gap-9 items-start"><div><p className="text-xs font-mono text-primary uppercase tracking-[.24em] mb-3">Contato</p><h2 className="text-3xl md:text-4xl font-bold tracking-tighter">Vamos construir algo útil?</h2><p className="text-muted-foreground mt-4 leading-relaxed max-w-lg">Estou disponível para conversar sobre oportunidades e projetos com Java 17+ / Spring Boot 3, Quarkus, Kotlin Android nativo e Flutter/Dart híbrido. Escolha o canal que fizer mais sentido para você.</p><a href="mailto:reinaldobarretosilva@gmail.com?subject=Contato%20pelo%20portfólio" className="neo-button inline-flex items-center gap-2 px-5 py-3 rounded-lg mt-7 text-sm font-semibold">Enviar e-mail <ArrowUpRight size={16} /></a><p className="flex items-center gap-2 text-xs text-muted-foreground font-mono mt-6"><MapPin size={14} className="text-primary" /> Navegantes/SC, Brasil</p></div><div className="space-y-3">{links.map(({ label, value, href, icon: Icon }, index) => <motion.a key={label} href={href} target={href.startsWith("http") ? "_blank" : undefined} rel={href.startsWith("http") ? "noopener noreferrer" : undefined} initial={{ opacity: 0, x: 15 }} whileInView={{ opacity: 1, x: 0 }} viewport={{ once: true }} transition={{ delay: index * .08 }} className="neo-mini-card block rounded-xl p-4 group"><div className="flex items-center gap-3"><span className="w-10 h-10 rounded-lg grid place-items-center bg-primary/10 border border-primary/25"><Icon size={18} className="text-primary" /></span><span className="min-w-0"><span className="block text-xs font-mono text-muted-foreground">{label}</span><span className="block text-sm mt-1 truncate group-hover:text-primary transition-colors">{value}</span></span><ArrowUpRight size={16} className="ml-auto text-muted-foreground group-hover:text-primary transition-colors" /></div></motion.a>)}</div></div></div></div></section>;
}
