source "https://rubygems.org"
ruby "3.3.0"

gem "rails",   "~> 7.2"
gem "pg",      "~> 1.1"
gem "puma",    "~> 6.0"
gem "rack-cors"
gem "bootsnap", require: false

group :development, :test do
  gem "rspec-rails"
  gem "factory_bot_rails"
  gem "faker"
end
