source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby "3.3.0"

gem "rails", "~> 7.2"
gem "pg", "~> 1.1"
gem "puma", "~> 6.0"
gem "devise"
gem "devise-jwt"
gem "rack-cors"
gem "jbuilder"
gem "bootsnap", require: false

group :development, :test do
  gem "rspec-rails"
  gem "factory_bot_rails"
  gem "faker"
  gem "shoulda-matchers"
  gem "pry-rails"
end
